version: "3.8"
services:
    app:
        build: .
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html
    web:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app